language: r
r:
- oldrel
- release
r_packages:
- covr
warnings_are_errors: false
os:
- linux
- osx
env:
- RSERVE=Rserve
branches:
  only: master
addons:
  apt:
    packages:
    - libssh2-1-dev
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo chown -R $(whoami) /usr/local ; brew
  install libgit2; fi
before_script:
- echo `ls -la`
- cd ..; mv Rserve* Rserve; cd Rserve; sh mkdist -i
- echo `ls -la`
- cd ..; mv Rserve Rserve-src; tar zxvf Rserve_*.tar.gz; cd Rserve
- echo `ls -la`
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib";
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"; fi
after_script:
- ps ax | grep Rserve
- cd tests; bash test-RserveBugJava.sh || travis_terminate 1;
- ps ax | grep Rserve
after_success:
- if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "linux")
  ]]; then Rscript -e 'covr::codecov()'; fi
before_deploy:
- if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]]; then git tag "$TRAVIS_OS_NAME"
  --force; fi
- if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "osx") ]];
  then R CMD INSTALL --build $PKG_TARBALL; fi
deploy:
  provider: releases
  api_key:
    secure: cNa7gQFvJ7ck8RawhSt6TOSjLCi3R+EDWGtgeTMsWgUSFIWuoo+vMfrYLjMmMqLpaQOhjglCDjDUfty/fNbU+w3QZLB9LfoKHtOOhpWxrXvwWTa2GJtLraVQmtqdFRPergAJAEU+zxPp9IzWXr/vTg+7VaHolC6ysLG0XkCD8CkccLn2J+nE3j8RIwuuWkw/TZYC9SysAaZSpaYNsXtCprkoRM0tko1I5/rK3/NJhooFFvh2Op2mnOO8o6VPJvi2paIntEnQmzrUC9xhWVNeN4CQyhBkg/QVjgXGcOFXB/N4iya3UPD3XxoTbQzi7WqIQztJUp0CGBGe9RAufcvvq5xDZZq/98GeH9stab+GllmawQAAOlMokrT7vfPwdBpo08U9mbq/kS281rSQq6FMUONbU03ugE9OLSqZB8On6KZuWz2e7azBTcgiytULcZwLbscg1rvP3AyKKeN4OxTM2UkmWw7syuMC+WrgH8a7lkP+ZczCzKB+mhfdvrEAnBPTUqoa9MTbSkY+dhR537fJG1f3Oo8ROBzNNcpM/m3YhNIN7c5rUecMUQPLsId/BpozOiHvSyh0I8mFpoPnFjhYGh9eMMSHqiv0KK5AnArcTCaryT5VE5OPmyloRmdLjGUNZuiA6CEztzTifN6kBpcSbFu5D33ZCP8R9JO4qiAkFuk=
  file: Rserve*
  on:
    repo: yannrichet/Rserve-1.7
  skip_cleanup: 'true'
