language: minimal
matrix:
  include:
    - name: "Linux R-3.5"
      os: linux
      dist: xenial
      env:
        - R_version="3.5"
    - name: "Linux R-4.0"
      os: linux
      dist: xenial
      env:
        - R_version="4.0"
    - name: "MacOS R-3.5"
      os: osx
      osx_image: xcode10.1
      env:
        - R_version="3.5"
    - name: "MacOS R-4.0"
      os: osx
      osx_image: xcode10.1
      env:
        - R_version="4.0"
    #- name: "Windows R-3.5"
    #  os: windows
    #  env:
    #    - R_version="3.5"
    #- name: "Windows R-4.0"
    #  os: windows
    #  env:
    #    - R_version="4.0"
    
before_script:
  - > 
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      #sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
      if [[ "$R_version" == "3.6" ]]; then 
        echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/" | sudo tee -a /etc/apt/sources.list;
      else 
        echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran40/" | sudo tee -a /etc/apt/sources.list; 
      fi
      sudo apt-get update -qq --allow-unauthenticated;
      sudo apt-get install r-recommended --allow-unauthenticated -y;
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      export HOMEBREW_NO_AUTO_UPDATE=1; 
      rm -f '/usr/local/include/c++'; 
      if [[ "$R_version" == "3.6" ]]; then 
        #brew install r;
        wd=$PWD;
        cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core;
        git reset --hard c3a244c627e;
        git checkout -b r-3.6.3;
        cd $wd;
      else
        brew install r;
      fi
      RH=`ls /usr/local/Cellar/r/`;
      echo `ls /usr/local/Cellar/r/$RH/bin`;
      export PATH=$PATH:/usr/local/Cellar/r/$RH/bin; 
      brew install libgit2
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      if [[ "$R_version" == "3.6" ]]; then 
        choco install r --version 3.6; fi
      else
        choco install r --version 4.0; fi
      fi
    fi

env:
  - RSERVE=Rserve
branches:
  only:
    master
    
before_script:
  - echo `ls -la`
  - cd ..; mv Rserve* Rserve; cd Rserve; sh mkdist -i
  - echo `ls -la`
  - cd ..; mv Rserve Rserve-src; tar zxvf Rserve_*.tar.gz; cd Rserve
  - echo `ls -la`
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"; export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"; fi

after_script:
  - ps ax | grep Rserve
  - cd tests; bash test-RserveBugJava.sh || travis_terminate 1;
  - ps ax | grep Rserve
  
after_success:
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "linux") ]]; then Rscript -e 'install.packages("covr", repos="https://cran.rstudio.com"); covr::codecov()'; fi
  
before_deploy:
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "osx") ]]; then R CMD INSTALL --build $PKG_TARBALL; fi
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "windows") ]]; then R CMD INSTALL --build $PKG_TARBALL; fi

deploy:
  provider: releases
  name: "$TRAVIS_OS_NAME_$R_version"
  api_key:
    secure: "lxbU0MSoVH7cduiL/fw6kZHT5Y/dsZE+RvbPohOPNKgh7NrvR+ztf10Y96uDcrDp14GS1pyrUqZjKYA21m2X4ntPzCZcoTl3yw6/BgGD9U7Mbv7/j85c5qnGXHjHN0gFXkOjj9CKjjauHIB7DvRHbWZD4M9eLyHlrwSD0PUxQkYa6O4rQsUEuICKNFdGcvbybHyzG7TG3/L7EiXpdMw9SPpQtIvF2AdhNu5ldsgqBCtGNx/3jPVV5/TIEuORXmHB+xcBPftK0Yz90yueYdLwFkGD8gQWswqdq7HR1oEel8bAvYCNDLxeOBRHHkk8MnlP1SkLQCjLKqdBC+JhwbindP6Bkg9FU8tfLshn0vtZq1ctitEFQ+Fjsocryc+1dotLd/t6QquBalZytlcLIU5Om163hZsANdTcjLTl/QWZFnsD0pgpYDbCmKMgNrgpe3yZhLWW+EUi0nAikdvLzwKcqi4KnGiV2HmxM1xT7NkCzA8IxKFgrKYG2F7SOANsg3YmG8dsVVXn2gt3tGfE3oBcLlRTbIf6wgvU4hrFOzUTARp+c9b3BP9IKI0qNEszgI4gD6A3fqefGysk4d/NiEyQujWxhwdAtI+JfjynX7h1iXv0X4fZfwwH5E33Oi0e7CfsmkkmHA+CQVZvVNh3QxdjScKaiRUO9Y/r4qDtJOToZJs="
  file_glob: true
  file: 
    - Rserve*.t*gz
    - Rserve*.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branch: master
